<?xml version="1.0" encoding="UTF-8"?><testrun name="ChapterControllerTest" project="backend" tests="2" started="2" failures="0" errors="1" ignored="0">
  <testsuite name="com.novelsbr.backend.controllers.ChapterControllerTest" time="3.036" displayname="ChapterControllerTest" uniqueid="[engine:junit-jupiter]/[class:com.novelsbr.backend.controllers.ChapterControllerTest]">
    <testcase name="preparingTestEnvironment" classname="com.novelsbr.backend.controllers.ChapterControllerTest" time="2.772" displayname="preparingTestEnvironment()" uniqueid="[engine:junit-jupiter]/[class:com.novelsbr.backend.controllers.ChapterControllerTest]/[method:preparingTestEnvironment()]"/>
    <testcase name="save" classname="com.novelsbr.backend.controllers.ChapterControllerTest" time="0.258" displayname="save()" uniqueid="[engine:junit-jupiter]/[class:com.novelsbr.backend.controllers.ChapterControllerTest]/[method:save()]">
      <error>org.springframework.security.authentication.BadCredentialsException: Usuário inexistente ou senha inválida&#13;
	at org.springframework.security.authentication.dao.DaoAuthenticationProvider.additionalAuthenticationChecks(DaoAuthenticationProvider.java:93)&#13;
	at org.springframework.security.authentication.dao.AbstractUserDetailsAuthenticationProvider.authenticate(AbstractUserDetailsAuthenticationProvider.java:147)&#13;
	at org.springframework.security.authentication.ProviderManager.authenticate(ProviderManager.java:182)&#13;
	at com.novelsbr.backend.controllers.ChapterControllerTest.getToken(ChapterControllerTest.java:101)&#13;
	at com.novelsbr.backend.controllers.ChapterControllerTest.save(ChapterControllerTest.java:125)&#13;
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)&#13;
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)&#13;
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)&#13;
&#13;
</error>
    </testcase>
  </testsuite>
</testrun>
